[2025-02-09T22:09:23.373+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T22:09:23.398+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.load_data manual__2025-02-09T22:09:10.018401+00:00 [queued]>
[2025-02-09T22:09:23.410+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.load_data manual__2025-02-09T22:09:10.018401+00:00 [queued]>
[2025-02-09T22:09:23.429+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2025-02-09T22:09:23.451+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): load_data> on 2025-02-09 22:09:10.018401+00:00
[2025-02-09T22:09:23.462+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=103) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-09T22:09:23.465+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL', 'load_data', 'manual__2025-02-09T22:09:10.018401+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpfnlh_ck5']
[2025-02-09T22:09:23.466+0000] {standard_task_runner.py:72} INFO - Started process 105 to run task
[2025-02-09T22:09:23.466+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask load_data
[2025-02-09T22:09:23.556+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL.load_data manual__2025-02-09T22:09:10.018401+00:00 [running]> on host b33347fa3e64
[2025-02-09T22:09:23.679+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T22:09:10.018401+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T22:09:10.018401+00:00'
[2025-02-09T22:09:23.682+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-09T22:09:23.683+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-09T22:09:23.683+0000] {logging_mixin.py:190} INFO - Current task name:load_data state:running start_date:2025-02-09 22:09:23.399436+00:00
[2025-02-09T22:09:23.684+0000] {logging_mixin.py:190} INFO - Dag name:ETL and current dag run status:running
[2025-02-09T22:09:23.684+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T22:09:23.829+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-09T22:09:23.847+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-09T22:09:23.848+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ETL, task_id=load_data, run_id=manual__2025-02-09T22:09:10.018401+00:00, execution_date=20250209T220910, start_date=20250209T220923, end_date=20250209T220923
[2025-02-09T22:09:23.864+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-09T22:09:23.864+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-09T22:09:23.865+0000] {logging_mixin.py:190} INFO - Dag name:ETL queued_at:2025-02-09 22:09:10.055893+00:00
[2025-02-09T22:09:23.866+0000] {logging_mixin.py:190} INFO - Task hostname:b33347fa3e64 operator:PythonOperator
[2025-02-09T22:09:23.924+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-02-09T22:09:23.946+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T22:09:23.950+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
